version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 99
    labels:
      - 'pr: dependencies'
  - package-ecosystem: 'npm'
    directory: '/website'
    schedule:
      interval: 'weekly' 
    open-pull-requests-limit: 0
    labels:
      - 'pr: dependencies'
