blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Requests
    url: https://mkeithx.pages.dev/feature-requests
    about: Casual Feature Requests
  - name: â“Simple Question
    url: https://github.com/mkeithX/mkeithx.github.io/issues/new/choose
    about: Use the tracker and submit an issue
    
